// ...existing code...
use App\Http\Controllers\Admin\AuditLogController;
// ...existing code...
Route::middleware(['auth:sanctum', 'role:admin'])->get('/admin/audit-logs', [AuditLogController::class, 'index'])->name('admin.audit-logs');
// ...existing code...

