"""Initial migration

Revision ID: 001_initial
Revises: 
Create Date: 2025-01-08 15:07:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fhir_id', sa.String(length=255), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('identifier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_id')
    )
    
    op.create_table('system_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('diagnostic_reports',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fhir_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('effective_datetime', sa.DateTime(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_id')
    )
    
    op.create_table('imaging_studies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fhir_id', sa.String(length=255), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('accession_number', sa.String(length=255), nullable=True),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_id'),
    sa.UniqueConstraint('study_instance_uid')
    )
    
    op.create_table('dicom_studies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('imaging_study_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=False),
    sa.Column('study_date', sa.DateTime(), nullable=True),
    sa.Column('study_time', sa.String(length=50), nullable=True),
    sa.Column('study_description', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('dicom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imaging_study_id'], ['imaging_studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_instance_uid')
    )
    
    op.create_table('ai_analyses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dicom_study_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('analysis_type', sa.String(length=100), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.String(length=50), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dicom_study_id'], ['dicom_studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analyses')
    op.drop_table('dicom_studies')
    op.drop_table('imaging_studies')
    op.drop_table('diagnostic_reports')
    op.drop_table('audit_logs')
    op.drop_table('system_configurations')
    op.drop_table('patients')
    # ### end Alembic commands ###